export default {
  index: 'Home',
  'getting-started': 'Getting Started',
  'user-guide': 'User Guide',
  integrations: 'Integrations',
  deployment: 'Deployment',
  'api-reference': 'API Reference',
  migration: 'Migration Guides',
  playground: 'Playground',
  contributing: 'Contributing',
  changelog: 'Changelog',
  faq: 'Faq',
  'getting-help': 'Getting Help',
  glossary: 'Glossary',
  troubleshooting: 'Troubleshooting',
}
